#!/usr/bin/env ruby

require "colorize"
require "/usr/local/lib/vf/util.rb"
require "/usr/local/lib/vf/test.rb"
require "/usr/local/lib/vf/sync.rb"

option = $*[0]
files = []

if option == "-a"
  files = Dir["**/*"]
else  
  diff       = `git diff develop --name-only`
  files = diff.split("\n")
  puts "\n#{files.size.to_s.magenta} Files\n\n"
  $files_all = files.freeze
end  

case option 
when "sync"
  Sync.sync files
when "-ld"
  Util.compare_methods(".", ARGV[1])  
when "-a"
  Util.grep files, $*[1]
  Util.open_file $*[1..-1].join(" "), files
when "g"
  Util.grep files, ARGV[1]
when "t"
  Test.testare files
when "/"
  Util.open_file $*[1], files
when "//"
  system files.inject("vim"){ |acc, file| "#{acc} #{file}" } 
when "c"  
  Util.clean files.select {|file| file.end_with?(".rb") } 
when "r"  
  files.select{|f| f.end_with?(".rb")}.each do |file|
    p = `rubocop #{file}`
    unless "#{p}".include? "no offense"
      system "rubocop #{file}"
      $stdin.gets.chomp
    end
  end
when "help", "-h", "--help"
  puts ""
  puts "-a        ... look around (grep + find)"
  puts "-ld [keyword] ... compare a function among classes"
  puts "sync      ... sync files"
  puts "c         ... clean"
  puts "g         ... grep"
  puts "t         ... test (ruby)"
  puts "r         ... rubocop"
  puts "/         ... open a file after reading it."
  puts "//         ... open all files after reading it."
  puts "help, -h ... help option"
  puts ""
else
  Util.open_file $*[0..-1].join(" "), files
end
