#!/usr/bin/env ruby

require "/usr/local/lib/vf/vim_find.rb"

vf = VimFind.new(ARGV)

vf.open(vf.first_arg, WIKIDIR) if vf.option == ":wio"

case vf.option
when "-w"
  vf.operate_wiki 
when "-wl"  
  vf.enlist_wiki(WIKIDIR, vf.first_arg)
when "-h", "--help"  
  puts "[keywords]: search files"
  puts "-w        : oprate local wiki"
  puts "-wl       : enlist local wiki"
  puts "-h        : show help"
else
  vf.search_all
end

